Class ks.lib.interop.router.HL7RoutingEngine Extends (EnsLib.HL7.MsgRouter.RoutingEngine, RoutingEngine)
{

Storage Default
{
<Data name="HL7RoutingEngineDefaultData">
<Subscript>"HL7RoutingEngine"</Subscript>
<Value name="1">
<Value>ContextRequestTarget</Value>
</Value>
<Value name="2">
<Value>ContextRequestTimeout</Value>
</Value>
<Value name="3">
<Value>ContextRequestTransform</Value>
</Value>
<Value name="4">
<Value>ActOnContextError</Value>
</Value>
<Value name="5">
<Value>ContextResponseTransform</Value>
</Value>
</Data>
<DefaultData>HL7RoutingEngineDefaultData</DefaultData>
<Type>%Storage.Persistent</Type>
}

}
