Class ks.lib.interop.router.VDocRoutingEngine Extends (EnsLib.MsgRouter.VDocRoutingEngine, RoutingEngine)
{

Storage Default
{
<Data name="VDocRoutingEngineDefaultData">
<Subscript>"VDocRoutingEngine"</Subscript>
<Value name="1">
<Value>ContextRequestTarget</Value>
</Value>
<Value name="2">
<Value>ContextRequestTimeout</Value>
</Value>
<Value name="3">
<Value>ContextRequestTransform</Value>
</Value>
<Value name="4">
<Value>ActOnContextError</Value>
</Value>
<Value name="5">
<Value>ContextResponseTransform</Value>
</Value>
</Data>
<DefaultData>VDocRoutingEngineDefaultData</DefaultData>
<Type>%Storage.Persistent</Type>
}

}
