 zn "%SYS"
 d ##class(Security.Users).UnExpireUserPasswords("*")

 s nameSpace = "USER"
 d ##class(%Library.EnsembleMgr).EnableNamespace(nameSpace)
 
 s ^SYS("Security","CSP","AllowPrefix","/csp/healthshare/user/","%UnitTest.")=1
 
 s $namespace = nameSpace

 s ^RepositoryRoot="/irisrun/repo"  
 s ^UnitTestResourcesRoot=^RepositoryRoot_"/resource/test"
 s ^UnitTestRoot=^RepositoryRoot_"/test"

 zpm "load /opt/irisbuild":1

 halt
