name: objectscriptquality
on: push

jobs:
  linux:
    name: Linux build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Execute ObjectScript Quality Analysis
      run: |        
        sudo cp ".github/certificates/*crt" /usr/local/share/ca-certificates/
        sudo update-ca-certificates
        wget https://raw.githubusercontent.com/litesolutions/objectscriptquality-jenkins-integration/master/iris-community-hook.sh
        sh ./iris-community-hook.sh
